package demo.dao.customers;

import demo.domain.customers.Customer;
import demo.domain.customers.CustomerExample;
import java.util.List;

public interface CustomerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    Customer selectByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customer record);
}