package demo.domain.customers;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_id
     *
     * @mbg.generated
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_name
     *
     * @mbg.generated
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_source
     *
     * @mbg.generated
     */
    private String custSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_industry
     *
     * @mbg.generated
     */
    private String custIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_level
     *
     * @mbg.generated
     */
    private String custLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_address
     *
     * @mbg.generated
     */
    private String custAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_phone
     *
     * @mbg.generated
     */
    private String custPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_id
     *
     * @return the value of cst_customer.cust_id
     *
     * @mbg.generated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_id
     *
     * @param custId the value for cst_customer.cust_id
     *
     * @mbg.generated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_name
     *
     * @return the value of cst_customer.cust_name
     *
     * @mbg.generated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_name
     *
     * @param custName the value for cst_customer.cust_name
     *
     * @mbg.generated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_source
     *
     * @return the value of cst_customer.cust_source
     *
     * @mbg.generated
     */
    public String getCustSource() {
        return custSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_source
     *
     * @param custSource the value for cst_customer.cust_source
     *
     * @mbg.generated
     */
    public void setCustSource(String custSource) {
        this.custSource = custSource == null ? null : custSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_industry
     *
     * @return the value of cst_customer.cust_industry
     *
     * @mbg.generated
     */
    public String getCustIndustry() {
        return custIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_industry
     *
     * @param custIndustry the value for cst_customer.cust_industry
     *
     * @mbg.generated
     */
    public void setCustIndustry(String custIndustry) {
        this.custIndustry = custIndustry == null ? null : custIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_level
     *
     * @return the value of cst_customer.cust_level
     *
     * @mbg.generated
     */
    public String getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_level
     *
     * @param custLevel the value for cst_customer.cust_level
     *
     * @mbg.generated
     */
    public void setCustLevel(String custLevel) {
        this.custLevel = custLevel == null ? null : custLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_address
     *
     * @return the value of cst_customer.cust_address
     *
     * @mbg.generated
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_address
     *
     * @param custAddress the value for cst_customer.cust_address
     *
     * @mbg.generated
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_phone
     *
     * @return the value of cst_customer.cust_phone
     *
     * @mbg.generated
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_phone
     *
     * @param custPhone the value for cst_customer.cust_phone
     *
     * @mbg.generated
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }
}